//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventSoft.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> categoriaid { get; set; }
        public Nullable<decimal> precioSinIva { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public string unidadVenta { get; set; }
        public Nullable<int> stock { get; set; }
    
        public virtual categoria categoria { get; set; }
    }
}
